### ISSUE TITLE
output format different from input format

### ISSUE THREAD

**Issue by zuhairak** [biladina/hijridatetime#1]
I am trying to convert a Gregorian date to Hijri Date, but single month digits are not getting prefixed with 0, How could we fix it

Here is the code I tried, output is 30-7-1399
````
<?php

use biladina\hijridatetime\HijriDateTime;

$dob = date('d-m-Y', strtotime('1979-06-24 03:00:00'));
echo $dob;
echo "\n";
$hijri = new HijriDateTime();
$hijriDOB =  $hijri->strToHijri($dob, 'd-m-Y');
echo $hijriDOB;
````

**Comment by biladina** [comment]
Hi, you are using wrong format, in `d-m-Y` format, `m` means month with prefix..

if you want to use month without prefix, you can use `d-n-Y` format..

your code must look like this, `$hijr->strToHijri($date, 'd-n-Y');`

hope this helps..

**Comment by zuhairak** [comment]
Thanks for the response, but I want month with prefix which is not happening, What could be the issue?

**Comment by biladina** [comment]
ah, okay, you want the output format same as the input format, which is `d-m-Y`..

its a bug, I will fix it..

**Comment by biladina** [comment]
you can try to re-install the package, it should be fixed now..

**Comment by zuhairak** [comment]
Thanks a lot man! Appreciate this
